### PR TITLE
Cat

### PR DESCRIPTION
**Pull request by cat40**
Added string functions to listf
Also fixed listf.find(). It was returning the value, instead of the index (I think the previous version did this too)
Added eqsplit() to newmath.py. It splits the equation at operators ('2+2'->['2', '+', '2'])
eqformat() is in the file, but commented out because it's not finished and has fatal compiling errors

### CODE REVIEW

**Comment by StardustGogeta** [comment]
I was wondering - why switch all the comments to strings? I had changed them to strings so they would look nicer and take up less space.

**Comment by cat40** [comment]
The comments on the new functions are multiple lines, so strings are a bit less annoying to read
I also like to separate the description of the functions from the descriptions of the code
Also, looking a default Python libraries, they seem to use strings as the standard
It's probably okay to keep them as comments though, if you want.

**Comment by StardustGogeta** [comment]
I do prefer the comments, and in the source code for Python I see a mix of both varieties. However, I believe that comments are marginally faster when run in the program, as supported by the attachment. Following this logic, is it okay to merge this and then go back and reformat the comments?
[speed.txt](https://github.com/StardustGogeta/joint-programming/files/319587/speed.txt)

**Comment by cat40** [comment]
It's fine with me if you change it to comments
I'm not sure they're faster though. I ran your script 5 times and got slower 3/5, and faster 2/5. 
It's very close and seems more random than anything else. However, that might just be my computer. Were your results more consistent?
results:
>>> 
2.96871556979
3.25026997046
>>> ================================ RESTART ================================
>>> 
2.61492192912
2.53114046876
>>> ================================ RESTART ================================
>>> 
2.7458591421
2.56439864122
>>> ================================ RESTART ================================
>>> 
2.75436825544
2.91055924749
>>> ================================ RESTART ================================
>>> 
2.70123519608
2.55321820521
>>>

**Comment by StardustGogeta** [comment]
My results were consistently faster with the comments, at around 0.880 sec vs. 0.910 sec with your strings.

**Comment by cat40** [comment]
Alright. I'm fine with changing to comments.

**Comment by StardustGogeta** [comment]
Yay! I will attempt to make the fixes. Also, I will make any necessary modifications to the new additions you made.

**Pull request merged**
